### ISSUE TITLE
Websockets error

### ISSUE THREAD

**Issue by rewtd** [secure-delivery/copi#15]
Sometimes (for security reasons) websockets are not available for clients to use. The Phoenix framework now supports a fallback to longpoll now so implementing this should not be too complication: https://github.com/phoenixframework/phoenix/issues/2914#:~:text=Longpoll%20Fallback%20has%20been%20officially%20implemented%20in%20Phoenix

**Comment by tobyirvine** [comment]
This is coming as part of the Phoenix 1.7 upgrade. Hopefully, quite soon.

**Comment by tobyirvine** [comment]
Long polling is now in.
